version: '3.7'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=pass123
    ports:
      - "3306:3306"
    restart: always
    networks:
      - "my-net"

networks:
  my-net:
    driver: bridge