version: '3.7'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=pass123
    ports:
      - "3306:3306"
    restart: always
    networks:
      - "my-net"


  keycloak-service:
    image: keycloak/keycloak:latest
    container_name: keycloak-service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    ports:
      - "8085:8085"
    command:
      - start-dev
      - --http-port=8085
    restart: always
    networks:
      - "my-net"

networks:
  my-net:
    driver: bridge